version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      androidx:
        patterns:
          - "androidx.*"
      compose:
        patterns:
          - "androidx.compose*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
